@host = http://127.0.0.1:8000/api/v1

# @name login
POST {{host}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "guest@example.com",
    "password": "12345678"
}

###

@accessToken = {{login.response.body.data.access_token}}
@refreshToken = {{login.response.body.data.refresh_token}}

###

# @name getBasicInfo
GET {{host}}/me/basic-info
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# @name createRole
POST {{host}}/roles
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{

}