@host = http://127.0.0.1:8000/api/v1

# @name login
POST {{host}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@example.com",
    "password": "12345678"
}

###

@accessToken = {{login.response.body.data.access_token}}
@refreshToken = {{login.response.body.data.refresh_token}}

###

# @name getBasicInfo
GET {{host}}/me/basic-info
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# @name getRoles
GET {{host}}/roles?page=1&size=10&sort=-created_at
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# @name createRole
POST {{host}}/roles
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Role001",
    "description": "",
    "is_admin": 0
}

###

# @name getRole
GET {{host}}/roles/24
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# @name updateRole
PUT {{host}}/roles/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Role001 Updated",
    "is_admin": 0
}

###

# @name destroyRole
DELETE {{host}}/roles/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# @name getNodes
GET {{host}}/nodes
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# @name createNode
POST {{host}}/nodes
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "label": "Node004",
    "description": "Description for Node004"
}

###

# @name getNode
GET {{host}}/nodes/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# @name updateNode
PUT {{host}}/nodes/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "label": "Node001 Updated",
    "description": "Description for Node001 Updated"
}

###

# @name destroyNode
DELETE {{host}}/nodes/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

###