@host = http://127.0.0.1:8000/api/v1

GET {{host}}/tools/placehold-images
Content-Type: application/json
Accept: application/json

{
    "width": 100,
    "height": 100,
    "bg": "#FF3355",
    "color": "#FFFFFF",
    "text": "Hinh"
}